### ISSUE TITLE
Middleware leaves items in buffer when # of items < BATCH_SIZE

### ISSUE THREAD

**Issue by stummjr** [monkeylearn/scrapy-monkeylearn#10]
When the number of items extracted by a spider is smaller than `BATCH_SIZE`, the `self.batch` buffer is not processed.

This happens because of [this condition](https://github.com/monkeylearn/scrapy-monkeylearn/blob/master/scrapy_monkeylearn/middlewares.py#L54) in `process_spider_output`:

    if len(self.items) > self.batch_size:

This same condition causes incomplete crawl results when the number of items scraped is larger than `BATCH_SIZE` but lower than `BATCH_SIZE * 2`. For example:

- `BATCH_SIZE`: 50
- number of scraped items: 90

In this scenario, the middleware will process the first 51 items and the remaining ones will stay in the buffer and will not be ever processed as the size of `self.items` will never reach `self.batch_size` again.

**Comment by chekunkov** [comment]
Fixed in https://github.com/scrapy-plugins/scrapy-monkeylearn/pull/13
